spring:
  application:
    name: product-service
  profiles:
    group:
      "local": "local, default-datasource, default-redis, eureka, openfeign, actuator"
      "docker": "docker, default-datasource, default-redis, eureka, openfeign, actuator"
      "prod": "prod, prod-datasource, prod-data-redis, prod-cache-redis, eureka, openfeign, actuator"
    active: "local"

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}