spring:
  datasource:
    url: jdbc:postgresql://${LOCAL_POSTGRESQL_HOST:localhost}:${LOCAL_POSTGRESQL_PORT:5432}/${LOCAL_DB_NAME:come2us}
    username: ${LOCAL_POSTGRESQL_USERNAME:developer}
    password: ${LOCAL_POSTGRESQL_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        hibernate.format_sql: true
        hibernate.highlight_sql: true
        hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 200
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
      encoding: UTF-8

file:
  storage: local
  upload-dir: ${user.dir}/uploads/
